modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="lexchange"
version="1.20.1-1.0.12"
displayName="Lite Exchange"
logoFile="lexchange.png"
authors="Lemon_Juiced & Scalar Team"

description='''
A lite retro-exchange-styled mod.
'''

[[dependencies.lexchange]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lexchange]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lexchange]]
    modId="lemon_core"
    mandatory=false
    versionRange="[1.20-1.0.11,)"
    ordering="NONE"
    side="BOTH"