modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="lexchange"
version="1.19.4-1.0.4"
displayName="Lite Exchange"
logoFile="mod_icon.png"
credits="Lemon_Juiced"
authors="Lemon_Juiced"

description='''
A lite retro-exchange-styled mod.
'''

[[dependencies.lexchange]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lexchange]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
