modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="lexchange"
version="1.20-1.0.8"
displayName="Lite Exchange"
logoFile="mod_icon.png"
credits="Lemon_Juiced"
authors="Lemon_Juiced"

description='''
A lite retro-exchange-styled mod.
'''

[[dependencies.lexchange]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lexchange]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lexchange]]
    modId="lemon_core"
    mandatory=false
    versionRange="[1.20-1.0.7,)"
    ordering="NONE"
    side="BOTH"